Control Flow
>>> from condition import *
>>> condition()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: condition() missing 1 required positional argument: 'x'
>>> condition(9)
True
>>> condition("")
False
>>> condition('')
False
>>> condition([])
False
>>> condition(0)
False